In [1]:
import numpy as np

In [2]:
mylist =[1,2,3,4,5]

In [3]:
print(mylist)

[1, 2, 3, 4, 5]


In [4]:
mylist2 = ["apple","banana","orange"]

In [5]:
print(mylist2)

['apple', 'banana', 'orange']


In [7]:
array1 = np.array(mylist)

In [8]:
array1

array([1, 2, 3, 4, 5])

In [9]:
array1[2]

3

In [12]:
arr = np.arange(1,11)

In [13]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
arr2 = np.arange(0,11)

In [17]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])